### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Yukaru-san** [DataManager-Go/DataManagerGUI#15]
**Golang**
- [ ] Add / Remove / Move Files between Group / Tag / NS
- [ ] Make files non-public again
- [ ] Create new Group
- [ ] Compressed dir upload
- [ ] Delete from keystore
- [ ] Update Tags when changing directory
- [ ] Create Tag
- [ ] Adjustable alternative server URL
- [x] Fix Preview
- [x] Publish File
- [x] Create new NS
- [x] Rename NS
- [x] Delete NS
- [x] Rename Group
- [x] Delete Group
- [x] Rename Tag
- [x] Delete Tag
- [x] Delete Multiple files at once

**Javascript**
- [ ] Fix unknown sorting error
- [ ] Add / Remove / Move Files between Group / Tag / NS
- [ ] File Information
- [ ] Adjustable alternative server URL
- [x] Fix unique File select on upload
- [x] Drag & Drop File / Directory upload
- [x] Rename FIle / Remove "Edit properties"
- [x] Sort by ID (or selected column) when reloading files
- [x] Recolor private file's "public name"
- [x] Make NS / Group RMB options fixed to sidebar
- [x] Make files non-public again
- [x] Focus Input Overlay's first field upon opening
- [x] Fix sorting by "IsPublic"
- [x] Fix rmb close between tags and page nav
- [x] Custom Yes/No Dialog
- [x] Fix autocompletion on upload
- [x] F5 to reload page
- [x] Create Tag
- [x] Rename Tag
- [x] Delete Tag
- [x] Create new NS
- [x] Rename NS
- [x] Delete NS
- [x] Create new Group
- [x] Rename Group
- [x] Delete Group
- [x] Compressed dir upload
- [x] Delete Multiple files at once
